name: Check Passport Dates

on:
  schedule:
    - cron: '*/50 * * * *'  # кожні 50 хвилин
  workflow_dispatch:        # дозволяє запуск вручну

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checker script
        env:
          ZENROWS_API_KEY: ${{ secrets.ZENROWS_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python passport_checker.py
